import type {TcpEvent} from "./tcp-model";
import {FlowCanvas} from "../canvas/FlowCanvas";
import {parseScene} from "../core/schema";
import {tcpScene} from "./tcp-model";
import "./tcp-views.css";

export type TcpView="handshake"|"encapsulation"|"network"|"reliability"|"flow"|"congestion";
export type TcpConfig={payload:number;mss:number;window:number;latency:number;drop:number|null;reorder:boolean};
export type Segment={id:number;seq:number;length:number;ack:number;dropped:boolean};
export function segmentsFor(config:TcpConfig):Segment[]{const count=Math.ceil(config.payload/config.mss);return Array.from({length:count},(_,i)=>{const length=Math.min(config.mss,config.payload-i*config.mss);return{id:i+1,seq:1001+i*config.mss,length,ack:1001+(i*config.mss)+length,dropped:config.drop===i+1}})}

export function TcpViewRenderer({view,event,eventIndex,config}:{view:TcpView;event:TcpEvent;eventIndex:number;config:TcpConfig}){const segments=segmentsFor(config);if(view==="handshake")return <Handshake eventIndex={eventIndex}/>;if(view==="encapsulation")return <Encapsulation eventIndex={eventIndex} event={event}/>;if(view==="network")return <FlowCanvas scene={parseScene(tcpScene(event))}/>;if(view==="reliability")return <Reliability segments={segments} reorder={config.reorder}/>;if(view==="flow")return <FlowControl segments={segments} window={config.window}/>;return <Congestion drop={config.drop}/>}

function Handshake({eventIndex}:{eventIndex:number}){const messages=[{label:"SYN",detail:"seq=1000",from:"client"},{label:"SYN + ACK",detail:"seq=5000 · ack=1001",from:"server"},{label:"ACK",detail:"seq=1001 · ack=5001",from:"client"}];return <div className="tcp-panel handshake-view"><div className="lifeline"><b>Client</b><small>192.168.1.8:52491</small><i/></div><div className="sequence-space">{messages.map((m,i)=><div className={`${m.from} ${eventIndex>=i+1?"visible":""}`} key={m.label} style={{top:`${24+i*28}%`}}><span>{m.label}<small>{m.detail}</small></span><svg viewBox="0 0 500 35" preserveAspectRatio="none"><defs><marker id={`arrow-${i}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10Z"/></marker></defs><line x1={m.from==="client"?0:500} y1="17" x2={m.from==="client"?500:0} y2="17" markerEnd={`url(#arrow-${i})`}/></svg></div>)}</div><div className="lifeline"><b>Server</b><small>203.0.113.10:443</small><i/></div></div>}

function Encapsulation({eventIndex,event}:{eventIndex:number;event:TcpEvent}){const depth=Math.min(4,Math.max(1,eventIndex));return <div className="tcp-panel encapsulation-view"><div className="envelope"><div className={depth>=4?"frame active":"frame"}><label>Ethernet frame</label><span>Dst MAC</span><div className={depth>=3?"ip active":"ip"}><label>IP packet</label><span>Src 192.168.1.8</span><span>Dst 203.0.113.10</span><div className={depth>=2?"segment active":"segment"}><label>TCP segment</label><span>Src 52491</span><span>Dst 443</span><span>SEQ {event.packet?.seq??1001}</span><div className="payload"><label>Application bytes</label><code>GET / HTTP/1.1</code></div></div></div><span>FCS</span></div></div><aside><span>ENCAPSULATION DEPTH</span><h3>{depth===1?"Application data":depth===2?"TCP adds delivery information":depth===3?"IP adds end-to-end addresses":"Link layer prepares one hop"}</h3><p>Each layer adds only the information required for its responsibility. The receiver removes these wrappers in reverse order.</p></aside></div>}

function Reliability({segments,reorder}:{segments:Segment[];reorder:boolean}){const ordered=reorder?[...segments].sort((a,b)=>a.id===1?1:b.id===1?-1:a.id-b.id):segments;return <div className="tcp-panel reliability-view"><div className="byte-axis"><span>Sender byte stream</span><div>{segments.map(s=><i key={s.id} style={{flex:s.length}}>{s.seq}–{s.ack-1}</i>)}</div></div><div className="transit"><span>IN TRANSIT</span>{ordered.map((s,i)=><div className={s.dropped?"segment-card dropped":"segment-card"} key={s.id} style={{"--delay":`${i*.08}s`} as React.CSSProperties}><b>SEG {s.id}</b><small>SEQ {s.seq}</small><small>LEN {s.length}</small><em>{s.dropped?"LOST":`ACK ${s.ack}`}</em></div>)}</div><div className="ack-rule"><b>Cumulative ACK</b><p>The receiver acknowledges only the next contiguous byte it expects. A later segment cannot close an earlier gap.</p></div></div>}

function FlowControl({segments,window}:{segments:Segment[];window:number}){return <div className="tcp-panel flow-view"><div className="buffer"><span>SENDER BUFFER</span><div>{segments.map((s,i)=><i className={i<window?"allowed":"waiting"} key={s.id}><b>{s.id}</b><small>{i<window?"may send":"wait"}</small></i>)}</div></div><div className="window-gate"><b>rwnd = {window} segments</b><span>Receiver advertises available space</span></div><div className="buffer receiver"><span>RECEIVER BUFFER</span><div>{Array.from({length:Math.max(6,segments.length)},(_,i)=><i className={i<window?"free":"reserved"} key={i}><small>{i<window?"free":"full"}</small></i>)}</div></div></div>}

function Congestion({drop}:{drop:number|null}){const values=drop?[1,2,4,8,4,5,6,7]:[1,2,4,8,9,10,11,12];const points=values.map((v,i)=>`${55+i*85},${325-v*22}`).join(" ");return <div className="tcp-panel congestion-view"><svg viewBox="0 0 720 380" role="img" aria-label="Congestion window over time"><g className="grid"><path d="M55 35V325H690 M55 270H690 M55 215H690 M55 160H690 M55 105H690 M55 50H690"/></g><text x="20" y="185" transform="rotate(-90 20 185)">congestion window (segments)</text><text x="330" y="365">round trips</text><polyline points={points}/>{values.map((v,i)=><g className={drop&&i===3?"loss-point":"point"} transform={`translate(${55+i*85} ${325-v*22})`} key={i}><circle r="7"/><text y="-13" textAnchor="middle">{v}</text></g>)}</svg><div><b>{drop?"Loss reduces the sending rate":"Successful delivery increases the window"}</b><p>Congestion control protects the network. It is separate from the receiver's advertised flow-control window.</p></div></div>}
