interface D1Statement { bind(...values: unknown[]): D1Statement; first<T=Record<string,unknown>>(): Promise<T|null>; run(): Promise<unknown> }
interface D1Database { prepare(sql:string): D1Statement }
interface AiBinding { run(model:string,input:Record<string,unknown>):Promise<unknown> }
interface Env { AI: AiBinding; DB: D1Database; ASSETS: { fetch(request: Request): Promise<Response> } }
interface WorkerContext { waitUntil(promise:Promise<unknown>):void }
const schema={type:"object",additionalProperties:false,properties:{title:{type:"string"},category:{type:"string"},level:{type:"string",enum:["Beginner","Beginner → Intermediate"]},summary:{type:"string"},analogy:{type:"string"},sections:{type:"array",minItems:3,maxItems:5,items:{type:"object",additionalProperties:false,properties:{heading:{type:"string"},body:{type:"string"}},required:["heading","body"]}},terms:{type:"array",minItems:3,maxItems:6,items:{type:"object",additionalProperties:false,properties:{term:{type:"string"},definition:{type:"string"}},required:["term","definition"]}},visualization:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["flow","timeline","stack","network","tree","comparison","cycle"]},title:{type:"string"},nodes:{type:"array",minItems:3,maxItems:7,items:{type:"object",additionalProperties:false,properties:{label:{type:"string"},detail:{type:"string"}},required:["label","detail"]}},steps:{type:"array",minItems:4,maxItems:8,items:{type:"string"}},actors:{type:"array",minItems:2,maxItems:6,items:{type:"object",additionalProperties:false,properties:{label:{type:"string"},role:{type:"string"}},required:["label","role"]}},events:{type:"array",minItems:4,maxItems:8,items:{type:"object",additionalProperties:false,properties:{from:{type:"integer",minimum:0,maximum:5},to:{type:"integer",minimum:0,maximum:5},label:{type:"string"},detail:{type:"string"},state:{type:"string"}},required:["from","to","label","detail","state"]}}},required:["type","title","nodes","steps","actors","events"]},tryIt:{type:"array",minItems:3,maxItems:5,items:{type:"string"}}},required:["title","category","level","summary","analogy","sections","terms","visualization","tryIt"]};
const DAILY_NEW_LESSON_LIMIT=20;
function lessonFromAi(data:any){const value=data?.response??data;if(value&&typeof value==="object")return value;if(typeof value!=="string")throw new Error("Workers AI returned no lesson");const cleaned=value.trim().replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/,"");const start=cleaned.indexOf("{"),end=cleaned.lastIndexOf("}");if(start<0||end<start)throw new Error("Workers AI returned invalid JSON");return JSON.parse(cleaned.slice(start,end+1))}
function validateLesson(lesson:any){if(!lesson?.title||!lesson?.category||!Array.isArray(lesson?.sections)||!lesson?.visualization?.events?.length)throw new Error("Incomplete lesson");const actorCount=lesson.visualization.actors?.length||0;if(actorCount<2||lesson.visualization.events.some((event:any)=>!Number.isInteger(event.from)||!Number.isInteger(event.to)||event.from<0||event.to<0||event.from>=actorCount||event.to>=actorCount))throw new Error("Invalid simulation");return lesson}
async function generateLesson(env:Env,prompt:string){const messages=[{role:"system",content:"You create accurate, beginner-friendly computer-science lessons as structured JSON. Return JSON only and follow the supplied schema exactly."},{role:"user",content:prompt}];try{return validateLesson(lessonFromAi(await env.AI.run("@cf/meta/llama-3.1-8b-instruct-fast",{messages,response_format:{type:"json_schema",json_schema:schema},max_tokens:2400,temperature:0.2})))}catch(firstError){console.warn("Structured generation failed; retrying",firstError);return validateLesson(lessonFromAi(await env.AI.run("@cf/meta/llama-3.1-8b-instruct-fast",{messages:[...messages,{role:"user",content:`Return one valid JSON object only. It must match this schema: ${JSON.stringify(schema)}`}],response_format:{type:"json_object"},max_tokens:2400,temperature:0.1})))}}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
function normalize(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9+#.\- ]/g," ").replace(/\s+/g," ").trim()}
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export default {async fetch(request:Request,env:Env,ctx:WorkerContext):Promise<Response>{
 const url=new URL(request.url);if(url.pathname!=="/api/concept")return env.ASSETS.fetch(request);if(request.method!=="POST")return json({error:"Use POST."},405);
 let concept="";try{const body=await request.json() as {concept?:unknown};concept=typeof body.concept==="string"?body.concept.trim():""}catch{return json({error:"Invalid request."},400)}
 if(concept.length<2||concept.length>120)return json({error:"Enter a concept between 2 and 120 characters."},400);const key=normalize(concept);if(key.length<2)return json({error:"Enter a valid programming or computer-science concept."},400);
 let existing:{id:number,content_json:string}|null;try{existing=await env.DB.prepare("SELECT id, content_json FROM concepts WHERE normalized_name = ? AND status = 'published' LIMIT 1").bind(key).first<{id:number,content_json:string}>()}catch(error){console.error("D1 lookup failed",error);return json({error:"The concept database is not connected correctly. Check the D1 database ID and migration.",code:"D1_LOOKUP_FAILED"},503)}
 if(existing){ctx.waitUntil(env.DB.prepare("UPDATE concepts SET hit_count = hit_count + 1, last_accessed_at = CURRENT_TIMESTAMP WHERE id = ?").bind(existing.id).run());try{return json({...JSON.parse(existing.content_json),_meta:{source:"database",cached:true}})}catch{return json({error:"This saved lesson needs to be regenerated."},500)}}
 const ipHash=await hash(request.headers.get("CF-Connecting-IP")||"unknown"),day=new Date().toISOString().slice(0,10);
 await env.DB.prepare("INSERT INTO generation_limits (ip_hash, day, generation_count) VALUES (?, ?, 1) ON CONFLICT(ip_hash, day) DO UPDATE SET generation_count = generation_count + 1").bind(ipHash,day).run();
 const usage=await env.DB.prepare("SELECT generation_count FROM generation_limits WHERE ip_hash = ? AND day = ?").bind(ipHash,day).first<{generation_count:number}>();if((usage?.generation_count||0)>DAILY_NEW_LESSON_LIMIT)return json({error:"You reached today's new-lesson limit. Saved lessons remain available."},429);
 const prompt=`Create an accurate lesson about the computer-science or programming concept: "${concept}". Write for a true beginner, but preserve important technical truth. If the term is ambiguous, interpret it in computing. If it is unrelated to computing, state that clearly. Build a mechanism simulation, not a decorative diagram. Actors are the real components involved (machines, layers, data structures, processes, variables, or services). Events are a chronological trace of what moves or changes between actors. Actor indexes in every from/to must be valid for the actors array. For an internal state change, from and to may be the same actor. Every event must name the visible token/action, explain the causal change, and give the resulting state. The nodes and steps provide a simpler overview of the same mechanism. Use plain English, one concrete analogy, and concise paragraphs.`;
 try{const lesson=await generateLesson(env,prompt),content=JSON.stringify(lesson);try{await env.DB.prepare("INSERT INTO concepts (normalized_name, display_name, category, content_json, source, status, hit_count, last_accessed_at) VALUES (?, ?, ?, ?, 'workers-ai', 'published', 1, CURRENT_TIMESTAMP) ON CONFLICT(normalized_name) DO UPDATE SET content_json = excluded.content_json, display_name = excluded.display_name, category = excluded.category, source = excluded.source, updated_at = CURRENT_TIMESTAMP, last_accessed_at = CURRENT_TIMESTAMP").bind(key,lesson.title,lesson.category,content).run()}catch(saveError){console.error("D1 save failed",saveError);return json({error:"The lesson was generated but could not be saved. Check that the D1 migration was applied.",code:"D1_SAVE_FAILED"},503)}return json({...lesson,_meta:{source:"workers-ai",cached:false}})}catch(error){console.error("Workers AI generation failed",error);return json({error:"Cloudflare AI could not format this lesson. Please try the search once more.",code:"AI_GENERATION_FAILED"},502)}
 }};
