interface D1Statement { bind(...values: unknown[]): D1Statement; first<T=Record<string,unknown>>(): Promise<T|null>; run(): Promise<unknown> }
interface D1Database { prepare(sql:string): D1Statement }
interface Env { OPENAI_API_KEY?: string; DB: D1Database; ASSETS: { fetch(request: Request): Promise<Response> } }
interface WorkerContext { waitUntil(promise:Promise<unknown>):void }
const schema={type:"object",additionalProperties:false,properties:{title:{type:"string"},category:{type:"string"},level:{type:"string",enum:["Beginner","Beginner → Intermediate"]},summary:{type:"string"},analogy:{type:"string"},sections:{type:"array",minItems:3,maxItems:5,items:{type:"object",additionalProperties:false,properties:{heading:{type:"string"},body:{type:"string"}},required:["heading","body"]}},terms:{type:"array",minItems:3,maxItems:6,items:{type:"object",additionalProperties:false,properties:{term:{type:"string"},definition:{type:"string"}},required:["term","definition"]}},visualization:{type:"object",additionalProperties:false,properties:{type:{type:"string",enum:["flow","timeline","stack","network","tree","comparison","cycle"]},title:{type:"string"},nodes:{type:"array",minItems:3,maxItems:7,items:{type:"object",additionalProperties:false,properties:{label:{type:"string"},detail:{type:"string"}},required:["label","detail"]}},steps:{type:"array",minItems:3,maxItems:7,items:{type:"string"}}},required:["type","title","nodes","steps"]},tryIt:{type:"array",minItems:3,maxItems:5,items:{type:"string"}}},required:["title","category","level","summary","analogy","sections","terms","visualization","tryIt"]};
const DAILY_NEW_LESSON_LIMIT=20;
function outputText(data:any){if(typeof data.output_text==="string")return data.output_text;for(const item of data.output||[])for(const content of item.content||[])if(content.type==="output_text")return content.text;return ""}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}
function normalize(value:string){return value.normalize("NFKC").toLowerCase().replace(/[^a-z0-9+#.\- ]/g," ").replace(/\s+/g," ").trim()}
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
export default {async fetch(request:Request,env:Env,ctx:WorkerContext):Promise<Response>{
 const url=new URL(request.url);if(url.pathname!=="/api/concept")return env.ASSETS.fetch(request);if(request.method!=="POST")return json({error:"Use POST."},405);
 let concept="";try{const body=await request.json() as {concept?:unknown};concept=typeof body.concept==="string"?body.concept.trim():""}catch{return json({error:"Invalid request."},400)}
 if(concept.length<2||concept.length>120)return json({error:"Enter a concept between 2 and 120 characters."},400);const key=normalize(concept);if(key.length<2)return json({error:"Enter a valid programming or computer-science concept."},400);
 const existing=await env.DB.prepare("SELECT id, content_json FROM concepts WHERE normalized_name = ? AND status = 'published' LIMIT 1").bind(key).first<{id:number,content_json:string}>();
 if(existing){ctx.waitUntil(env.DB.prepare("UPDATE concepts SET hit_count = hit_count + 1, last_accessed_at = CURRENT_TIMESTAMP WHERE id = ?").bind(existing.id).run());try{return json({...JSON.parse(existing.content_json),_meta:{source:"database",cached:true}})}catch{return json({error:"This saved lesson needs to be regenerated."},500)}}
 if(!env.OPENAI_API_KEY)return json({error:"This lesson is not saved yet and AI generation has not been connected."},503);
 const ipHash=await hash(request.headers.get("CF-Connecting-IP")||"unknown"),day=new Date().toISOString().slice(0,10);
 await env.DB.prepare("INSERT INTO generation_limits (ip_hash, day, generation_count) VALUES (?, ?, 1) ON CONFLICT(ip_hash, day) DO UPDATE SET generation_count = generation_count + 1").bind(ipHash,day).run();
 const usage=await env.DB.prepare("SELECT generation_count FROM generation_limits WHERE ip_hash = ? AND day = ?").bind(ipHash,day).first<{generation_count:number}>();if((usage?.generation_count||0)>DAILY_NEW_LESSON_LIMIT)return json({error:"You reached today's new-lesson limit. Saved lessons remain available."},429);
 const prompt=`Create an accurate lesson about the computer-science or programming concept: "${concept}". Write for a true beginner, but preserve important technical truth. If the term is ambiguous, interpret it in computing. If it is unrelated to computing, state that clearly. The visualization must model the mechanism, not decorate it. Each node detail and step must explain a causal change. Use plain English, one concrete analogy, and concise paragraphs.`;
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"authorization":`Bearer ${env.OPENAI_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:prompt,reasoning:{effort:"low"},max_output_tokens:2400,text:{format:{type:"json_schema",name:"concept_lesson",strict:true,schema}}})});const apiData=await response.json() as any;if(!response.ok)return json({error:apiData?.error?.message||"The lesson service is temporarily unavailable."},502);
 try{const lesson=JSON.parse(outputText(apiData)),content=JSON.stringify(lesson);await env.DB.prepare("INSERT INTO concepts (normalized_name, display_name, category, content_json, source, status, hit_count, last_accessed_at) VALUES (?, ?, ?, ?, 'ai', 'published', 1, CURRENT_TIMESTAMP) ON CONFLICT(normalized_name) DO UPDATE SET content_json = excluded.content_json, display_name = excluded.display_name, category = excluded.category, updated_at = CURRENT_TIMESTAMP, last_accessed_at = CURRENT_TIMESTAMP").bind(key,lesson.title,lesson.category,content).run();return json({...lesson,_meta:{source:"openai",cached:false}})}catch{return json({error:"The lesson could not be formatted. Please try again."},502)}
 }};
