import {useEffect,useMemo,useState} from "react";
import {ArrowLeftRight,BookOpen,Boxes,Braces,ChevronRight,Clock3,Code2,Cpu,Database,Globe2,HardDrive,Layers3,Loader2,LockKeyhole,Network,Pause,Play,RotateCcw,Search,Server,ShieldCheck,Waypoints,X,Zap} from "lucide-react";

type Phase={title:string,short:string,detail:string,why:string,packets:{from:"client"|"server",label:string,sub:string,kind?:string}[]};
const phases:Phase[]=[
 {title:"Ports & sockets",short:"Find the right program",detail:"An IP address finds the computer. A port finds the program inside it. Together, source IP + source port + destination IP + destination port identify this conversation.",why:"Your browser chooses a temporary source port; HTTPS usually listens on destination port 443.",packets:[]},
 {title:"Three-way handshake",short:"Agree to communicate",detail:"SYN proposes a starting sequence number. SYN-ACK accepts and proposes the server’s number. ACK confirms both directions are ready.",why:"TCP is full-duplex: each side tracks its own independent byte sequence.",packets:[{from:"client",label:"SYN",sub:"seq=1000"},{from:"server",label:"SYN · ACK",sub:"seq=5000 ack=1001"},{from:"client",label:"ACK",sub:"ack=5001"}]},
 {title:"Segmentation",short:"Split bytes into pieces",detail:"TCP sees an ordered stream of bytes, then splits it into segments small enough for the network. Sequence numbers describe byte positions—not packet numbers.",why:"If bytes 1001–2460 are sent, the next segment can begin at sequence 2461.",packets:[{from:"client",label:"DATA",sub:"seq=1001 len=1460"},{from:"client",label:"DATA",sub:"seq=2461 len=1460"},{from:"client",label:"DATA",sub:"seq=3921 len=580"}]},
 {title:"ACK & ordering",short:"Confirm received bytes",detail:"The receiver reorders segments and sends a cumulative ACK: the number of the next byte it expects.",why:"ACK 3921 means every byte through 3920 arrived—even if the network delivered segments out of order.",packets:[{from:"client",label:"seq 2461",sub:"arrives first"},{from:"client",label:"seq 1001",sub:"fills the gap"},{from:"server",label:"ACK 3921",sub:"all bytes contiguous"}]},
 {title:"Loss & retransmission",short:"Recover missing data",detail:"If an ACK does not arrive before a timer expires—or duplicate ACKs reveal a gap—the sender retransmits the missing bytes.",why:"Reliability comes from detecting loss and sending again, not from the network guaranteeing delivery.",packets:[{from:"client",label:"DATA",sub:"seq=3921",kind:"lost"},{from:"server",label:"ACK 3921",sub:"still waiting"},{from:"client",label:"RETRANSMIT",sub:"seq=3921"}]},
 {title:"Flow control",short:"Protect the receiver",detail:"The receive window tells the sender how much free buffer space remains. The sender keeps unacknowledged data within that advertised limit.",why:"Flow control prevents a fast sender from overwhelming a slow receiving application.",packets:[{from:"server",label:"ACK · WIN",sub:"window=4 segments"}]},
 {title:"Congestion control",short:"Protect the network",detail:"TCP starts cautiously, grows its congestion window when delivery succeeds, and reduces it when loss suggests the network is crowded.",why:"The usable send amount is the smaller of the receive window and congestion window.",packets:[{from:"client",label:"cwnd 1",sub:"send 1"},{from:"client",label:"cwnd 2",sub:"send 2"},{from:"client",label:"cwnd 4",sub:"send 4"}]},
 {title:"Connection teardown",short:"Close both directions",detail:"FIN means “I have no more bytes to send.” Because TCP is full-duplex, each direction closes independently with FIN and ACK.",why:"TIME_WAIT lets delayed packets expire and permits retransmission of the final ACK.",packets:[{from:"client",label:"FIN",sub:"client finished"},{from:"server",label:"ACK",sub:"confirmed"},{from:"server",label:"FIN",sub:"server finished"},{from:"client",label:"ACK",sub:"closed"}]},
];
const catalogue={
 "Networks":["Transport layer","IP & routing","DNS resolution","HTTP lifecycle","TLS encryption","WebSockets"],
 "Data structures":["Arrays","Linked lists","Stacks & queues","Hash tables","Trees","Graphs"],
 "Computer systems":["CPU instructions","Memory & cache","Processes & threads","Files & storage","Operating systems","Virtual machines"],
 "Software":["Variables & memory","Functions & call stack","Object-oriented code","APIs","Databases & indexes","Git & branches"]
};
const comparison=[{name:"TCP",icon:"✓",connection:"Connection-based",delivery:"Reliable + ordered",speed:"More overhead",best:"Web pages, files, email"},{name:"UDP",icon:"→",connection:"No connection",delivery:"Best effort",speed:"Very low overhead",best:"Games, voice, live video"},{name:"QUIC",icon:"⚡",connection:"Secure by default",delivery:"Reliable streams over UDP",speed:"Fast setup",best:"HTTP/3 and modern web"}];
type Generated={title:string,category:string,level:string,summary:string,analogy:string,sections:{heading:string,body:string}[],terms:{term:string,definition:string}[],visualization:{type:string,title:string,nodes:{label:string,detail:string}[],steps:string[],actors?:{label:string,role:string}[],events?:{from:number,to:number,label:string,detail:string,state:string}[]},tryIt:string[]};

export default function App(){
 const [phase,setPhase]=useState(0),[playing,setPlaying]=useState(false),[packetStep,setPacketStep]=useState(0),[window,setWindow]=useState(4),[speed,setSpeed]=useState(1200),[query,setQuery]=useState(""),[ask,setAsk]=useState(""),[generated,setGenerated]=useState<Generated|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const current=phases[phase]; const visible=packetStep;
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setPacketStep(s=>{if(s>=current.packets.length){setPlaying(false);return s}return s+1}),speed);return()=>clearInterval(timer)},[playing,speed,current.packets.length]);
 const filtered=useMemo(()=>Object.entries(catalogue).map(([g,x])=>[g,x.filter(v=>v.toLowerCase().includes(query.toLowerCase()))] as const),[query]);
 function select(i:number){setPhase(i);setPacketStep(0);setPlaying(false)}
 async function loadConcept(name:string){if(!name.trim()||loading)return;setAsk(name);setLoading(true);setError("");try{const response=await fetch("/api/concept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({concept:name.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not generate this lesson.");setGenerated(data);setTimeout(()=>document.querySelector("#generated")?.scrollIntoView({behavior:"smooth"}),50)}catch(err){setError(err instanceof Error?err.message:"Could not generate this lesson.");setTimeout(()=>document.querySelector("#library-feedback")?.scrollIntoView({behavior:"smooth",block:"center"}),50)}finally{setLoading(false)}}
 async function explore(e:React.FormEvent){e.preventDefault();await loadConcept(ask)}
 return <div className="app">
  <header><a className="logo" href="#top"><span><BookOpen/></span><b>Kitab<small lang="ar" dir="rtl">كتاب</small></b></a><nav><a href="#lab">Chapters</a><a href="#library">Concept library</a><a href="#compare">Compare protocols</a></nav><div className="level"><BookOpen/>Beginner edition</div></header>
  <main id="top">
   <section className="hero"><div><p className="overline">A LIVING BOOK OF COMPUTER SCIENCE</p><h1>Open any idea.<br/><em>See how it works.</em></h1><p>Search any computer-science or programming concept. Kitab writes a clear chapter for you, then turns the mechanism into an interactive model.</p><form className="concept-search" onSubmit={explore}><Search/><input aria-label="Concept to explain" value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Open a chapter: recursion, Docker, DNS…"/><button disabled={loading}>{loading?<Loader2 className="spin"/>:<ChevronRight/>}<span>{loading?"Writing chapter":"Open chapter"}</span></button></form>{error&&<p className="search-error">{error}</p>}<div className="suggestions"><span>Bookmarks:</span>{["Recursion","Kubernetes","B-tree index","JWT"].map(x=><button onClick={()=>setAsk(x)} key={x}>{x}</button>)}</div></div><div className="hero-system"><div className="orbit o1"><Globe2/></div><div className="orbit o2"><Server/></div><div className="orbit o3"><Database/></div><span className="pulse p1"/><span className="pulse p2"/><div className="core"><BookOpen/><b>Kitab</b><small>knowledge in motion</small></div></div></section>
   <section className="stats"><div><strong>24</strong><span>built-in concepts</span></div><div><strong>∞</strong><span>searchable concepts</span></div><div><strong>8</strong><span>TCP stages</span></div><div><strong>0</strong><span>knowledge assumed</span></div></section>
   {generated&&<GeneratedLesson data={generated} close={()=>setGenerated(null)}/>} 

   <section id="lab" className="tcp-lab">
    <div className="section-title"><span>INTERACTIVE LAB 01</span><h2>TCP & the transport layer</h2><p>Follow an entire reliable conversation—from choosing a port to closing the connection.</p></div>
    <div className="lab-layout">
     <aside className="phase-list"><p>THE CONNECTION JOURNEY</p>{phases.map((p,i)=><button key={p.title} className={phase===i?"active":""} onClick={()=>select(i)}><span>{String(i+1).padStart(2,"0")}</span><div><b>{p.title}</b><small>{p.short}</small></div><ChevronRight/></button>)}</aside>
     <div className="simulator">
      <div className="sim-head"><div><span>STAGE {phase+1} OF {phases.length}</span><h3>{current.title}</h3></div><div className="status"><i/>TCP connection</div></div>
      <TcpStackScene packets={current.packets} visible={visible} phase={phase}/>
      {phase===5&&<div className="window-control"><label>Advertised receive window: <b>{window} segments</b></label><input aria-label="Receive window" type="range" min="1" max="8" value={window} onChange={e=>setWindow(+e.target.value)}/><div>{Array.from({length:8},(_,i)=><i className={i<window?"open":""} key={i}/>)}</div></div>}
      <div className="sim-controls"><button onClick={()=>{setPlaying(false);setPacketStep(0)}}><RotateCcw/>Reset</button><button disabled={!current.packets.length||packetStep>=current.packets.length} onClick={()=>{setPlaying(false);setPacketStep(x=>x+1)}}>Step →</button><button className="play" disabled={!current.packets.length} onClick={()=>{if(packetStep>=current.packets.length)setPacketStep(0);setPlaying(p=>!p)}}>{playing?<><Pause/>Pause</>:<><Play/>Play journey</>}</button><label>Speed <select value={speed} onChange={e=>setSpeed(+e.target.value)}><option value="1800">Slow</option><option value="1200">Normal</option><option value="650">Fast</option></select></label><span>{visible}/{current.packets.length||1} events</span></div>
      <div className="explanation"><div><span>WHAT IS HAPPENING?</span><p>{current.detail}</p></div><div><span>WHY IT MATTERS</span><p>{current.why}</p></div></div>
      <div className="phase-nav"><button disabled={phase===0} onClick={()=>select(phase-1)}>← Previous</button><span>{phases.map((_,i)=><i className={i===phase?"active":""} key={i}/>)}</span><button disabled={phase===phases.length-1} onClick={()=>select(phase+1)}>Next stage →</button></div>
     </div>
    </div>
   </section>

   <section id="compare" className="compare"><div className="section-title"><span>THE TRANSPORT TOOLBOX</span><h2>TCP is not the only choice</h2><p>Applications choose different transport behavior depending on what matters most.</p></div><div className="protocols">{comparison.map((x,i)=><article className={i===0?"featured":""} key={x.name}><div className="protocol-icon">{x.icon}</div><h3>{x.name}</h3><dl><div><dt>Setup</dt><dd>{x.connection}</dd></div><div><dt>Delivery</dt><dd>{x.delivery}</dd></div><div><dt>Trade-off</dt><dd>{x.speed}</dd></div><div><dt>Often used for</dt><dd>{x.best}</dd></div></dl></article>)}</div></section>

   <section id="library" className="library"><div className="library-head"><div className="section-title"><span>CONCEPT LIBRARY</span><h2>Explore the whole system</h2><p>Start anywhere. Each topic connects a visual model to the code and real-world behavior.</p></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search concepts…"/></label></div>{(loading||error)&&<div id="library-feedback" className={`library-feedback ${error?"failed":""}`}>{loading?<><Loader2 className="spin"/><div><b>Building “{ask}”</b><span>Cloudflare AI is creating the lesson and simulation…</span></div></>:<><X/><div><b>Could not open the lesson</b><span>{error}</span></div></>}</div>}<div className="catalogue">{filtered.map(([group,items],gi)=><div key={group}><h3>{[<Network/>,<Boxes/>,<Cpu/>,<Code2/>][gi]}{group}</h3>{items.map((x,i)=>{const ConceptIcon=[Waypoints,Layers3,HardDrive,Braces,Database,LockKeyhole][i%6];return <button disabled={loading} className={loading&&ask===x?"loading":""} onClick={()=>void loadConcept(x)} key={x}><span>{loading&&ask===x?<Loader2 className="spin"/>:<ConceptIcon size={18}/>}</span><b>{x}</b><small>{loading&&ask===x?"Building lesson…":"Open lesson"}</small><ChevronRight/></button>})}</div>)}</div></section>
   <section className="learning"><div><ShieldCheck/><h3>Accurate, not watered down</h3><p>Simple language without removing the technical details that make the idea true.</p></div><div><Zap/><h3>Learn by changing things</h3><p>Send packets, resize windows, reorder data, and see the consequence immediately.</p></div><div><Clock3/><h3>Move at your pace</h3><p>Every animation can be stepped through and replayed as often as you need.</p></div></section>
  </main>
  <footer><a className="logo" href="#top"><span><BookOpen/></span><b>Kitab<small lang="ar" dir="rtl">كتاب</small></b></a><p>Every concept deserves a clear page.</p></footer>
 </div>
}

function TcpStackScene({packets,visible,phase}:{packets:Phase["packets"],visible:number,phase:number}){const layers=["Application","Transport · TCP","Internet · IP","Link · Ethernet"],pdu=["DATA","SEGMENT","PACKET","FRAME"];const event=packets[Math.max(0,visible-1)];const direction=event?.from==="server"?"return":"out";const progress=packets.length?Math.min(visible/packets.length,1):0;return <div className="stack-scene"><div className="computer"><div className="machine-title"><Code2/><span><b>Computer A · sender</b><small>Browser · 192.168.1.8</small></span></div>{layers.map((x,i)=><div className={`osi-layer ${phase===0&&i===1?"focus":""}`} key={x}><span>L{4-i}</span><b>{x}</b><small>{i===0?"creates the request":i===1?"adds ports, sequence and ACK":i===2?"adds source and destination IP":"adds local MAC addresses"}</small><i>{pdu[i]}</i></div>)}</div><div className="packet-path"><div className="path-down"/><div className="medium"><Globe2/><b>Routers</b><small>read the IP header and forward the packet</small></div>{event&&<div key={`${phase}-${visible}`} className={`packet-orbit ${direction}`} style={{"--progress":progress} as React.CSSProperties}><b>{event.label}</b><small>{event.sub}</small><i>{direction==="out"?"ENCAPSULATE ↓ · TRANSMIT → · DECAPSULATE ↑":"ENCAPSULATE ↓ · RETURN ← · DECAPSULATE ↑"}</i></div>}{!packets.length&&<div className="socket-card"><span>SOCKET PAIR</span><b>:52491</b><ArrowLeftRight/><b>:443</b></div>}</div><div className="computer server-stack"><div className="machine-title"><Server/><span><b>Computer B · receiver</b><small>Server · 203.0.113.10</small></span></div>{[...layers].reverse().map((x,i)=>{const original=3-i;return <div className={`osi-layer ${phase===0&&i===2?"focus":""}`} key={x}><span>L{i+1}</span><b>{x}</b><small>{original===0?"delivers bytes to the server":original===1?"checks ports, order and ACK":original===2?"checks the destination IP":"checks frame and removes it"}</small><i>{pdu[original]}</i></div>})}</div></div>}

type Point={x:number,y:number};
function visualPositions(type:string,count:number):Point[]{
 if(type==="stack")return Array.from({length:count},(_,i)=>({x:50,y:14+i*(72/Math.max(count-1,1))}));
 if(type==="tree")return Array.from({length:count},(_,i)=>i===0?{x:50,y:13}:{x:14+((i-1)%3)*36,y:i<4?52:86});
 if(type==="cycle"||type==="network")return Array.from({length:count},(_,i)=>{const a=(Math.PI*2*i/count)-Math.PI/2;return{x:50+Math.cos(a)*36,y:50+Math.sin(a)*37}});
 if(type==="comparison")return Array.from({length:count},(_,i)=>({x:i%2?72:28,y:22+Math.floor(i/2)*34}));
 if(type==="timeline")return Array.from({length:count},(_,i)=>({x:12+i*(76/Math.max(count-1,1)),y:i%2?66:34}));
 return Array.from({length:count},(_,i)=>({x:12+i*(76/Math.max(count-1,1)),y:50}));
}

function GeneratedLesson({data,close}:{data:Generated,close:()=>void}){
 const nodes=data.visualization.nodes||[];
 const actors=data.visualization.actors||nodes.map(n=>({label:n.label,role:n.detail}));
 const events=data.visualization.events||data.visualization.steps.map((detail,i)=>({from:i%Math.max(actors.length,1),to:(i+1)%Math.max(actors.length,1),label:`Step ${i+1}`,detail,state:"changed"}));
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false);
 const active=events[step],positions=visualPositions(data.visualization.type,actors.length),from=positions[active?.from]||positions[0],to=positions[active?.to]||from;
 useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setStep(s=>s>=events.length-1?(setPlaying(false),s):s+1),1600);return()=>clearInterval(timer)},[playing,events.length]);
 const tokenStyle=active?({"--x1":`${from.x}%`,"--y1":`${from.y}%`,"--x2":`${to.x}%`,"--y2":`${to.y}%`} as React.CSSProperties):undefined;
 return <section className="generated" id="generated">
  <div className="generated-top"><div><span>{data.category} · {data.level}</span><h2>{data.title}</h2><p>{data.summary}</p></div><button aria-label="Close generated lesson" onClick={close}><X/></button></div>
  <div className="generated-grid"><div className="dynamic-visual"><div className="visual-title"><span>{data.visualization.type.toUpperCase()} SIMULATOR</span><b>{data.visualization.title}</b></div>
   <div className={`mechanism-map ${data.visualization.type}`}>
    <svg aria-hidden="true" viewBox="0 0 100 100" preserveAspectRatio="none">{events.map((e,i)=>{const a=positions[e.from],b=positions[e.to];return a&&b?<line key={i} className={i===step?"active":""} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}</svg>
    {actors.map((a,i)=><button style={{left:`${positions[i].x}%`,top:`${positions[i].y}%`}} className={`${i===active?.from?"sending":""} ${i===active?.to?"receiving":""}`} key={i} onClick={()=>{const found=events.findIndex(e=>e.from===i||e.to===i);if(found>=0){setPlaying(false);setStep(found)}}}><span>{i+1}</span><b>{a.label}</b><small>{a.role}</small></button>)}
    {active&&<div key={step} className="travel-token" style={tokenStyle}><Zap/><b>{active.label}</b></div>}
   </div>
   <div className="event-detail"><span>RESULTING STATE · {active?.state||"ready"}</span><h3>{active?.label}</h3><p>{active?.detail||data.visualization.steps[step]}</p></div>
   <div className="trace-strip">{events.map((e,i)=><button className={i===step?"active":""} onClick={()=>{setPlaying(false);setStep(i)}} key={i}><span>{i+1}</span><b>{e.label}</b></button>)}</div>
   <div className="player-controls"><button onClick={()=>{setPlaying(false);setStep(0)}}><RotateCcw/> Reset</button><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0}>← Step</button><button className="play" onClick={()=>{if(step===events.length-1)setStep(0);setPlaying(p=>!p)}}>{playing?<Pause/>:<Play/>}{playing?"Pause":"Play simulation"}</button><button onClick={()=>setStep(s=>Math.min(events.length-1,s+1))} disabled={step===events.length-1}>Next →</button><span>{step+1} / {events.length}</span></div>
  </div><div className="lesson-text"><div className="analogy"><span>THE SIMPLE PICTURE</span><p>{data.analogy}</p></div>{data.sections.map((s,i)=><article key={i}><small>{String(i+1).padStart(2,"0")}</small><div><h3>{s.heading}</h3><p>{s.body}</p></div></article>)}</div></div>
  <div className="generated-bottom"><div><h3>Words to know</h3>{data.terms.map(t=><p key={t.term}><b>{t.term}</b><span>{t.definition}</span></p>)}</div><div><h3>Try changing the model</h3>{data.tryIt.map((x,i)=><p key={i}><span>{i+1}</span>{x}</p>)}</div></div>
 </section>
}
