import {useMemo,useState} from "react";
import {ArrowLeftRight,BookOpen,Boxes,Braces,ChevronRight,Clock3,Code2,Cpu,Database,Globe2,HardDrive,Layers3,Loader2,LockKeyhole,Network,Play,RotateCcw,Search,Server,ShieldCheck,Waypoints,X,Zap} from "lucide-react";

type Phase={title:string,short:string,detail:string,why:string,packets:{from:"client"|"server",label:string,sub:string,kind?:string}[]};
const phases:Phase[]=[
 {title:"Ports & sockets",short:"Find the right program",detail:"An IP address finds the computer. A port finds the program inside it. Together, source IP + source port + destination IP + destination port identify this conversation.",why:"Your browser chooses a temporary source port; HTTPS usually listens on destination port 443.",packets:[]},
 {title:"Three-way handshake",short:"Agree to communicate",detail:"SYN proposes a starting sequence number. SYN-ACK accepts and proposes the server’s number. ACK confirms both directions are ready.",why:"TCP is full-duplex: each side tracks its own independent byte sequence.",packets:[{from:"client",label:"SYN",sub:"seq=1000"},{from:"server",label:"SYN · ACK",sub:"seq=5000 ack=1001"},{from:"client",label:"ACK",sub:"ack=5001"}]},
 {title:"Segmentation",short:"Split bytes into pieces",detail:"TCP sees an ordered stream of bytes, then splits it into segments small enough for the network. Sequence numbers describe byte positions—not packet numbers.",why:"If bytes 1001–2460 are sent, the next segment can begin at sequence 2461.",packets:[{from:"client",label:"DATA",sub:"seq=1001 len=1460"},{from:"client",label:"DATA",sub:"seq=2461 len=1460"},{from:"client",label:"DATA",sub:"seq=3921 len=580"}]},
 {title:"ACK & ordering",short:"Confirm received bytes",detail:"The receiver reorders segments and sends a cumulative ACK: the number of the next byte it expects.",why:"ACK 3921 means every byte through 3920 arrived—even if the network delivered segments out of order.",packets:[{from:"client",label:"seq 2461",sub:"arrives first"},{from:"client",label:"seq 1001",sub:"fills the gap"},{from:"server",label:"ACK 3921",sub:"all bytes contiguous"}]},
 {title:"Loss & retransmission",short:"Recover missing data",detail:"If an ACK does not arrive before a timer expires—or duplicate ACKs reveal a gap—the sender retransmits the missing bytes.",why:"Reliability comes from detecting loss and sending again, not from the network guaranteeing delivery.",packets:[{from:"client",label:"DATA",sub:"seq=3921",kind:"lost"},{from:"server",label:"ACK 3921",sub:"still waiting"},{from:"client",label:"RETRANSMIT",sub:"seq=3921"}]},
 {title:"Flow control",short:"Protect the receiver",detail:"The receive window tells the sender how much free buffer space remains. The sender keeps unacknowledged data within that advertised limit.",why:"Flow control prevents a fast sender from overwhelming a slow receiving application.",packets:[{from:"server",label:"ACK · WIN",sub:"window=4 segments"}]},
 {title:"Congestion control",short:"Protect the network",detail:"TCP starts cautiously, grows its congestion window when delivery succeeds, and reduces it when loss suggests the network is crowded.",why:"The usable send amount is the smaller of the receive window and congestion window.",packets:[{from:"client",label:"cwnd 1",sub:"send 1"},{from:"client",label:"cwnd 2",sub:"send 2"},{from:"client",label:"cwnd 4",sub:"send 4"}]},
 {title:"Connection teardown",short:"Close both directions",detail:"FIN means “I have no more bytes to send.” Because TCP is full-duplex, each direction closes independently with FIN and ACK.",why:"TIME_WAIT lets delayed packets expire and permits retransmission of the final ACK.",packets:[{from:"client",label:"FIN",sub:"client finished"},{from:"server",label:"ACK",sub:"confirmed"},{from:"server",label:"FIN",sub:"server finished"},{from:"client",label:"ACK",sub:"closed"}]},
];
const catalogue={
 "Networks":["Transport layer","IP & routing","DNS resolution","HTTP lifecycle","TLS encryption","WebSockets"],
 "Data structures":["Arrays","Linked lists","Stacks & queues","Hash tables","Trees","Graphs"],
 "Computer systems":["CPU instructions","Memory & cache","Processes & threads","Files & storage","Operating systems","Virtual machines"],
 "Software":["Variables & memory","Functions & call stack","Object-oriented code","APIs","Databases & indexes","Git & branches"]
};
const comparison=[{name:"TCP",icon:"✓",connection:"Connection-based",delivery:"Reliable + ordered",speed:"More overhead",best:"Web pages, files, email"},{name:"UDP",icon:"→",connection:"No connection",delivery:"Best effort",speed:"Very low overhead",best:"Games, voice, live video"},{name:"QUIC",icon:"⚡",connection:"Secure by default",delivery:"Reliable streams over UDP",speed:"Fast setup",best:"HTTP/3 and modern web"}];
type Generated={title:string,category:string,level:string,summary:string,analogy:string,sections:{heading:string,body:string}[],terms:{term:string,definition:string}[],visualization:{type:string,title:string,nodes:{label:string,detail:string}[],steps:string[]},tryIt:string[]};

export default function App(){
 const [phase,setPhase]=useState(0),[playing,setPlaying]=useState(false),[packetStep,setPacketStep]=useState(0),[window,setWindow]=useState(4),[query,setQuery]=useState(""),[ask,setAsk]=useState(""),[generated,setGenerated]=useState<Generated|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const current=phases[phase]; const visible=playing?current.packets.length:packetStep;
 const filtered=useMemo(()=>Object.entries(catalogue).map(([g,x])=>[g,x.filter(v=>v.toLowerCase().includes(query.toLowerCase()))] as const),[query]);
 function select(i:number){setPhase(i);setPacketStep(0);setPlaying(false)}
 async function loadConcept(name:string){if(!name.trim()||loading)return;setAsk(name);setLoading(true);setError("");try{const response=await fetch("/api/concept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({concept:name.trim()})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Could not generate this lesson.");setGenerated(data);setTimeout(()=>document.querySelector("#generated")?.scrollIntoView({behavior:"smooth"}),50)}catch(err){setError(err instanceof Error?err.message:"Could not generate this lesson.")}finally{setLoading(false)}}
 async function explore(e:React.FormEvent){e.preventDefault();await loadConcept(ask)}
 return <div className="app">
  <header><a className="logo" href="#top"><span><Braces/></span><b>Code Atlas</b></a><nav><a href="#lab">Labs</a><a href="#library">Concept library</a><a href="#compare">Compare protocols</a></nav><div className="level"><BookOpen/>Beginner path</div></header>
  <main id="top">
   <section className="hero"><div><p className="overline">Interactive computer science</p><h1>What do you want<br/><em>to understand?</em></h1><p>Search any computer-science or programming concept. Code Atlas will build a simple, detailed lesson and an interactive visual model for it.</p><form className="concept-search" onSubmit={explore}><Search/><input aria-label="Concept to explain" value={ask} onChange={e=>setAsk(e.target.value)} placeholder="Try: garbage collection, recursion, Docker…"/><button disabled={loading}>{loading?<Loader2 className="spin"/>:<ChevronRight/>}<span>{loading?"Building lesson":"Explain it"}</span></button></form>{error&&<p className="search-error">{error}</p>}<div className="suggestions"><span>Try:</span>{["Recursion","Kubernetes","B-tree index","JWT"].map(x=><button onClick={()=>setAsk(x)} key={x}>{x}</button>)}</div></div><div className="hero-system"><div className="orbit o1"><Globe2/></div><div className="orbit o2"><Server/></div><div className="orbit o3"><Database/></div><span className="pulse p1"/><span className="pulse p2"/><div className="core"><Network/><b>Any concept</b><small>made visible</small></div></div></section>
   <section className="stats"><div><strong>24</strong><span>built-in concepts</span></div><div><strong>∞</strong><span>searchable concepts</span></div><div><strong>8</strong><span>TCP stages</span></div><div><strong>0</strong><span>knowledge assumed</span></div></section>
   {generated&&<GeneratedLesson data={generated} close={()=>setGenerated(null)}/>} 

   <section id="lab" className="tcp-lab">
    <div className="section-title"><span>INTERACTIVE LAB 01</span><h2>TCP & the transport layer</h2><p>Follow an entire reliable conversation—from choosing a port to closing the connection.</p></div>
    <div className="lab-layout">
     <aside className="phase-list"><p>THE CONNECTION JOURNEY</p>{phases.map((p,i)=><button key={p.title} className={phase===i?"active":""} onClick={()=>select(i)}><span>{String(i+1).padStart(2,"0")}</span><div><b>{p.title}</b><small>{p.short}</small></div><ChevronRight/></button>)}</aside>
     <div className="simulator">
      <div className="sim-head"><div><span>STAGE {phase+1} OF {phases.length}</span><h3>{current.title}</h3></div><div className="status"><i/>TCP connection</div></div>
      <div className="network-scene">
       <div className="endpoint"><div><Code2/></div><b>Browser</b><small>192.168.1.8:{phase===0?"52 491":"52491"}</small></div>
       <div className="wire"><div className="wire-line"/>{current.packets.slice(0,visible).map((p,i)=><div key={i} className={`segment s${i} ${p.from} ${p.kind||""}`}><b>{p.label}</b><small>{p.sub}</small></div>)}{!current.packets.length&&<div className="socket-card"><span>SOCKET</span><b>192.168.1.8:52491</b><ArrowLeftRight/><b>203.0.113.10:443</b></div>}</div>
       <div className="endpoint server"><div><Server/></div><b>Web server</b><small>203.0.113.10:443</small></div>
      </div>
      {phase===5&&<div className="window-control"><label>Advertised receive window: <b>{window} segments</b></label><input aria-label="Receive window" type="range" min="1" max="8" value={window} onChange={e=>setWindow(+e.target.value)}/><div>{Array.from({length:8},(_,i)=><i className={i<window?"open":""} key={i}/>)}</div></div>}
      <div className="sim-controls"><button onClick={()=>{setPlaying(false);setPacketStep(0)}}><RotateCcw/>Reset</button><button className="play" disabled={!current.packets.length} onClick={()=>{setPlaying(false);setPacketStep(x=>x>=current.packets.length?0:x+1)}}>{packetStep>=current.packets.length?<><RotateCcw/>Replay</>:<><Play/>Send next segment</>}</button><span>{visible}/{current.packets.length||1} events</span></div>
      <div className="explanation"><div><span>WHAT IS HAPPENING?</span><p>{current.detail}</p></div><div><span>WHY IT MATTERS</span><p>{current.why}</p></div></div>
      <div className="phase-nav"><button disabled={phase===0} onClick={()=>select(phase-1)}>← Previous</button><span>{phases.map((_,i)=><i className={i===phase?"active":""} key={i}/>)}</span><button disabled={phase===phases.length-1} onClick={()=>select(phase+1)}>Next stage →</button></div>
     </div>
    </div>
   </section>

   <section id="compare" className="compare"><div className="section-title"><span>THE TRANSPORT TOOLBOX</span><h2>TCP is not the only choice</h2><p>Applications choose different transport behavior depending on what matters most.</p></div><div className="protocols">{comparison.map((x,i)=><article className={i===0?"featured":""} key={x.name}><div className="protocol-icon">{x.icon}</div><h3>{x.name}</h3><dl><div><dt>Setup</dt><dd>{x.connection}</dd></div><div><dt>Delivery</dt><dd>{x.delivery}</dd></div><div><dt>Trade-off</dt><dd>{x.speed}</dd></div><div><dt>Often used for</dt><dd>{x.best}</dd></div></dl></article>)}</div></section>

   <section id="library" className="library"><div className="library-head"><div className="section-title"><span>CONCEPT LIBRARY</span><h2>Explore the whole system</h2><p>Start anywhere. Each topic connects a visual model to the code and real-world behavior.</p></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search concepts…"/></label></div><div className="catalogue">{filtered.map(([group,items],gi)=><div key={group}><h3>{[<Network/>,<Boxes/>,<Cpu/>,<Code2/>][gi]}{group}</h3>{items.map((x,i)=><button onClick={()=>void loadConcept(x)} key={x}><span>{[Waypoints,Layers3,HardDrive,Braces,Database,LockKeyhole][i%6]({size:18})}</span><b>{x}</b><small>Open lesson</small><ChevronRight/></button>)}</div>)}</div></section>
   <section className="learning"><div><ShieldCheck/><h3>Accurate, not watered down</h3><p>Simple language without removing the technical details that make the idea true.</p></div><div><Zap/><h3>Learn by changing things</h3><p>Send packets, resize windows, reorder data, and see the consequence immediately.</p></div><div><Clock3/><h3>Move at your pace</h3><p>Every animation can be stepped through and replayed as often as you need.</p></div></section>
  </main>
  <footer><a className="logo" href="#top"><span><Braces/></span><b>Code Atlas</b></a><p>Computer science, made visible.</p></footer>
 </div>
}

function GeneratedLesson({data,close}:{data:Generated,close:()=>void}){const [step,setStep]=useState(0),[node,setNode]=useState(0);const nodes=data.visualization.nodes;return <section className="generated" id="generated"><div className="generated-top"><div><span>{data.category} · {data.level}</span><h2>{data.title}</h2><p>{data.summary}</p></div><button aria-label="Close generated lesson" onClick={close}><X/></button></div><div className="generated-grid"><div className="dynamic-visual"><div className="visual-title"><span>INTERACTIVE MODEL</span><b>{data.visualization.title}</b></div><div className={`dynamic-nodes ${data.visualization.type}`}>{nodes.map((n,i)=><button key={i} className={i===node?"active":""} onClick={()=>setNode(i)}><span>{i+1}</span><b>{n.label}</b>{i<nodes.length-1&&<ChevronRight/>}</button>)}</div>{nodes[node]&&<div className="node-detail"><strong>{nodes[node].label}</strong><p>{nodes[node].detail}</p></div>}<div className="step-player"><button onClick={()=>setStep(s=>s===0?data.visualization.steps.length-1:s-1)}>←</button><div><span>STEP {step+1} OF {data.visualization.steps.length}</span><p>{data.visualization.steps[step]}</p></div><button onClick={()=>setStep(s=>(s+1)%data.visualization.steps.length)}>→</button></div></div><div className="lesson-text"><div className="analogy"><span>THE SIMPLE PICTURE</span><p>{data.analogy}</p></div>{data.sections.map((s,i)=><article key={i}><small>{String(i+1).padStart(2,"0")}</small><div><h3>{s.heading}</h3><p>{s.body}</p></div></article>)}</div></div><div className="generated-bottom"><div><h3>Words to know</h3>{data.terms.map(t=><p key={t.term}><b>{t.term}</b><span>{t.definition}</span></p>)}</div><div><h3>Try changing the model</h3>{data.tryIt.map((x,i)=><p key={i}><span>{i+1}</span>{x}</p>)}</div></div></section>}
