import {useEffect,useMemo,useState} from "react";
import {BookOpen,Check,ChevronLeft,ChevronRight,FlaskConical,Lightbulb,Pause,Play,RotateCcw,Trophy,X} from "lucide-react";
import type {Chapter} from "./curated";
import {LessonEngine} from "./lesson-engines";
import "./learning-studio.css";

type Mode="learn"|"predict"|"explore"|"check"|"review";

export function LearningStudio({chapter,close}:{chapter:Chapter;close:()=>void}){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(false),[mode,setMode]=useState<Mode>("learn"),[experiment,setExperiment]=useState(false),[answer,setAnswer]=useState<number|null>(null),[completed,setCompleted]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem(`kitab-progress-${chapter.slug}`)||"[]")}catch{return[]}});
 const current=chapter.steps[step],last=step===chapter.steps.length-1;
 const percent=Math.round((new Set([...completed,step]).size/chapter.steps.length)*100);
 const answers=useMemo(()=>[current.state,"Nothing changes","The system immediately stops"],[current.state]);
 useEffect(()=>{if(!playing)return;const id=setTimeout(()=>{if(last){setPlaying(false);setMode("predict")}else setStep(s=>s+1)},1500);return()=>clearTimeout(id)},[playing,last,step]);
 useEffect(()=>{setAnswer(null);setMode("learn")},[step]);
 function mark(index:number){const next=Array.from(new Set([...completed,index]));setCompleted(next);localStorage.setItem(`kitab-progress-${chapter.slug}`,JSON.stringify(next))}
 function go(next:number){mark(step);setPlaying(false);setStep(Math.max(0,Math.min(chapter.steps.length-1,next)))}
 function reset(){setPlaying(false);setStep(0);setMode("learn");setExperiment(false);setAnswer(null)}
 return <section id="curated-chapter" className="learning-studio">
  <header className="studio-head"><div><span>{chapter.family} · GUIDED LAB</span><h2>{chapter.title}</h2><p>{chapter.summary}</p></div><div className="studio-progress"><b>{percent}%</b><span><i style={{width:`${percent}%`}}/></span><small>{completed.length} of {chapter.steps.length} scenes completed</small></div><button aria-label="Close lesson" onClick={close}><X/></button></header>
  <div className="studio-shell">
   <aside className="lesson-map"><div className="map-title"><BookOpen/><span><b>Lesson map</b><small>One idea at a time</small></span></div>{chapter.steps.map((s,i)=><button className={`${i===step?"active":""} ${completed.includes(i)?"done":""}`} onClick={()=>go(i)} key={s.title}><span>{completed.includes(i)?<Check/>:i+1}</span><div><b>{s.title}</b><small>{i===step?"Learning now":completed.includes(i)?"Completed":"Not started"}</small></div></button>)}</aside>
   <main className="studio-workspace"><div className="scene-head"><span>SCENE {step+1} OF {chapter.steps.length}</span><h3>{current.title}</h3><p>{current.detail}</p></div><LessonEngine key={`${chapter.slug}-${step}`} mode={chapter.mode} step={step} changed={experiment}/><div className="studio-controls"><button onClick={reset}><RotateCcw/>Reset</button><button onClick={()=>go(step-1)} disabled={step===0}><ChevronLeft/>Previous</button><button className="primary" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause/>:<Play/>}{playing?"Pause":"Auto play"}</button><button onClick={()=>last?(mark(step),setMode("review")):go(step+1)}>{last?"Finish lesson":"Next scene"}<ChevronRight/></button></div></main>
   <aside className="learning-panel"><div className="mode-tabs">{(["learn","predict","explore","check"] as Mode[]).map(x=><button className={mode===x?"active":""} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div>{mode==="learn"&&<div className="panel-content"><Lightbulb/><span>MENTAL MODEL</span><h3>{current.title}</h3><p>{chapter.analogy}</p><div className="truth"><b>What is actually happening</b><p>{current.detail}</p></div><button onClick={()=>setMode("predict")}>Make a prediction <ChevronRight/></button></div>}{mode==="predict"&&<div className="panel-content"><FlaskConical/><span>PREDICT BEFORE RUNNING</span><h3>What state comes next?</h3><p>Choose an answer before advancing the simulation.</p><div className="answer-list">{answers.map((x,i)=><button className={answer===i?i===0?"correct":"wrong":""} onClick={()=>setAnswer(i)} key={x}><i>{String.fromCharCode(65+i)}</i>{x}{answer===i&&i===0&&<Check/>}</button>)}</div>{answer!==null&&<p className={answer===0?"feedback good":"feedback"}>{answer===0?"Correct. You identified the state produced by this scene.":"Not quite. Follow which component owns the state, then try again."}</p>}</div>}{mode==="explore"&&<div className="panel-content"><FlaskConical/><span>CHANGE THE SYSTEM</span><h3>{chapter.experiment}</h3><p>{experiment?chapter.changed:chapter.normal}</p><button className={experiment?"experiment-on":""} onClick={()=>setExperiment(v=>!v)}>{experiment?"Restore normal behavior":"Run the experiment"}</button><small>Changing this does not change the lesson step. You can compare both states safely.</small></div>}{mode==="check"&&<div className="panel-content"><Check/><span>KNOWLEDGE CHECK</span><h3>Explain it in one sentence</h3><p>What changed in this scene, and which component owns the new state?</p><textarea aria-label="Your explanation" placeholder="Write your explanation here…"/><button onClick={()=>{mark(step);setMode(last?"review":"learn");if(!last)go(step+1)}}>{last?"Complete lesson":"Complete scene"}</button></div>}{mode==="review"&&<div className="panel-content review"><Trophy/><span>LESSON COMPLETE</span><h3>You finished {chapter.title}</h3><p>You can now review any scene, repeat experiments, or explain the mechanism without the animation.</p><dl><div><dt>Core idea</dt><dd>{chapter.summary}</dd></div><div><dt>Experiment</dt><dd>{chapter.changed}</dd></div></dl><button onClick={reset}>Review from the beginning</button></div>}</aside>
  </div>
 </section>
}
